name: Download Windows wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip tools
        run: python -m pip install --upgrade pip

      - name: Download wheels
        run: |
          mkdir win_packages
          pip download -r requirements.txt -d win_packages

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win_whl
          path: win_packages
